# Deployment for rest services test.
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: restservices
spec:
  selector:
    matchLabels:
      app: restservices
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: restservices
    spec:
      containers:
      - name: restservices
        image: jbcarpenter1/docker-test
        ports:
        - containerPort: 8080
---
# Service for rest services test.
apiVersion: v1
kind: Service
metadata:
  name: restservices-service
spec:
  selector:
    app: restservices
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080