apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: restservices-deployment
spec:
  selector:
    matchLabels:
      app: restservices
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: restservices
    spec:
      containers:
      - name: restservices-container
        image: jbcarpenter1/docker-test
        ports:
        - containerPort: 8080